version: "3.7"

services:
  database:
    image: postgres
    container_name: prisma_deliveries
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma_deliveries
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: delivery
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local